Report generated using Genoppi from Lage Lab
<br>
https://github.com/lagelab/Genoppi
<br>
<br>
<h4>Venn diagram - Genes of Interest</h4>
<br>
<br>
<b>Labels - single gene loci SNPs</b>
```{r warning = FALSE, echo = FALSE, comment = NA}
a <- paste0("pull down ∩ HGNC database (", nrow(params$f), ")")
b <- paste0("A = pull down subset of ", params$c, "<FDR<", params$d, " and ", params$i, 
                                                   "<logFC<", params$j, " (", nrow(params$g), ")")
c <- paste0("B = Single-gene-loci genes in HGNC database (", nrow(params$o), ")")
c(a, b, c)
```
<br>
<br>
```{r warning = FALSE, echo = FALSE}
grid.newpage()
grid.draw(params$k)
```
<br>
<br>
<b>Labels - Multi genes loci SNPs</b>
```{r warning = FALSE, echo = FALSE, comment = NA}
a <- paste0("pull down ∩ HGNC database (", nrow(params$f), ")")
b <- paste0("A = pull down subset of ", params$c, "<FDR<", params$d, " and ", params$i, 
                                                   "<logFC<", params$j, " (", nrow(params$g), ")")
c <- paste0("B = Multi-genes-loci genes in HGNC database (", nrow(params$p), ")")
c(a, b, c)
```
<br>
<br>
```{r warning = FALSE, echo = FALSE}
grid.newpage()
grid.draw(params$l)
```
<br>
<br>
<b>Labels - All SNPs</b>
```{r warning = FALSE, echo = FALSE, comment = NA}
a <- paste0("pull down ∩ HGNC database (", nrow(params$f), ")")
b <- paste0("A = pull down subset of ", params$c, "<FDR<", params$d, " and ", params$i, 
                                                   "<logFC<", params$j, " (", nrow(params$g), ")")
c <- paste0("B = Mapped genes in HGNC database (", nrow(params$h), ")")
```
<br>
<br>
```{r warning = FALSE, echo = FALSE}
grid.newpage()
grid.draw(params$a)
```
<br>
<br>
<b>Overlapping genes</b>
```{r warning = FALSE, echo = FALSE, comment=NA}
params$b
```
